package project.euler
/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */
object Problem002 extends App {
  println("Project Euler - problem 002")
  def fib(a: Int = 1, b: Int = 2): Stream[Int] = a #:: fib(b,a+b) // append to the stream
  println(fib().takeWhile({ _ < 4000000}).filter({ _ % 2 == 0}).sum)
}

